# Generated by Django 6.0.5 on 2026-07-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physio_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='angle_summaries',
            field=models.JSONField(blank=True, default=dict, help_text='{angleName: {min: float, max: float, mean: float}} — per-session angle stats for trend tracking'),
        ),
    ]
